name: Build application container from peerDependency
run-name: Generate o-platform ${{ inputs.client_ref }} for api-server peerDependency by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      client_ref:
        description: "A ref from this repository, CirclesUBI/o-platform."
        required: true
        type: string

jobs:
  read-packageJson:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      packageJson: ${{ steps.readPackageJson.outputs.packageJson }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.client_ref }}

      - id: readPackageJson
        run: |
          server_ref=jq '.peerDependencies."api-server"' ./package.json
          echo "server_ref=$server_ref" >> "${GITHUB_OUTPUT}"
  echo-packageJson:
    runs-on: ubuntu-latest
    needs: read-packageJson
    steps:
      -
        run: echo {{needs.read-packageJson.outputs.server_ref}}
  call-build-workflow:
    if: needs.read-packageJson.outputs.server_ref = "cf79a81"
    uses: CirclesUBI/o-platform/.github/workflows/build-container.yml@main
    needs: [read-packageJson, echo-packageJson]
    with:
      server_ref: ${{needs.read-packageJson.outputs.server_ref}}
      client_ref: ${{inputs.client_ref}}
    secrets: inherit