name: Build application container from peerDependency
run-name: Generate o-platform ${{ inputs.client_ref }} for api-server peerDependency by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      client_ref:
        description: "A ref from this repository, CirclesUBI/o-platform."
        required: true
        type: string

jobs:
  read-packageJson:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      packageJson: ${{ steps.readPackageJson.outputs.packageJson }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.client_ref }}

      - id: readPackageJson
        run: |
          echo "server_ref=$(cat ./package.json | jq '.peerDependencies.circlesapi')" >> "${GITHUB_OUTPUT}"
  call-build-workflow:
    uses: CirclesUBI/o-platform/.github/workflows/build-container.yml@main
    needs: read-packageJson
    with:
      server_ref: ${{needs.read-packageJson.outputs.server_ref}}
      client_ref: ${{inputs.client_ref}}
    secrets: inherit