name: Build application container from peerDependency
run-name: Generate o-platform build of ${{ inputs.client_ref }} for api-server peerDependency from ${{ github.ref }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      client_ref:
        description: "A ref from this repository, CirclesUBI/o-platform."
        required: true
        type: string

jobs:
  read-packageJson:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      server_ref: ${{ steps.readPackageJson.outputs.server_ref }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.client_ref }}

      - name: Read package.json, get server_ref
        id: readPackageJson
        run: |
          server_ref=$(jq -r '.peerDependencies."api-server"' ./package.json)
          echo "server_ref=$server_ref"
          echo "server_ref=$server_ref" >> "${GITHUB_OUTPUT}"
  echo-server_ref:
    name: echo server_ref
    runs-on: ubuntu-latest
    needs: read-packageJson
    steps:
      -
        run: echo ${{needs.read-packageJson.outputs.server_ref}}
  call-build-workflow:
    name: Trigger container build
    uses: CirclesUBI/o-platform/.github/workflows/build-container.yml@main
    needs: [read-packageJson, echo-server_ref]
    with:
      server_ref: ${{needs.read-packageJson.outputs.server_ref}}
      client_ref: ${{inputs.client_ref}}
    secrets: inherit
