name: Build application container from peerDependency
run-name: Generate o-platform ${{ inputs.client_ref }} for api-server peerDependency by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      client_ref:
        description: "A ref from this repository, CirclesUBI/o-platform."
        required: true
        type: string

jobs:
  read-packageJson:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      packageJson: ${{ steps.readPackageJson.outputs.packageJson }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.client_ref }}

      - id: readPackageJson
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "packageJson<<${delimiter}" >> "${GITHUB_OUTPUT}"
          cat ./package.json >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
  echo-packageJson:
    runs-on: ubuntu-latest
    needs: read-packageJson
    steps:
      -
        run: echo ${{needs.read-packageJson.outputs.packageJson}}
  call-build-workflow:
    uses: CirclesUBI/o-platform/.github/workflows/build-container.yml@main
    needs: read-packageJson
    with:
      server_ref: ${{fromJson(needs.read-packageJson.outputs.packageJson).peerDependencies.api-server}}
      client_ref: ${{inputs.client_ref}}
