name: deploy dev
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check svelte-i18n-keys
      uses: circlesland/CheckI18NKeys@v0.1.3-dev
      with:
        master_json: 'shell/src/i18n/lang/en.json'
        file_types: 'ts,svelte'
        default_language_prefix: 'en.'